"use client";
import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import logo from '/public/images/logo.png';
import Image from "next/image";
import { useEffect, useState } from "react";
import Link from "next/link";
import { usePathname } from 'next/navigation';

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

// export const metadata: Metadata = {
//   title: "Create Next App",
//   description: "Generated by create next app",
// };

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>)

{
  const pathname = usePathname();
  const hideHeader = pathname.includes("/components/pages/signup")
  const [userData, setUserData] = useState(null);
  const [loading, setLoading] = useState(true);

  useEffect(() => {
    fetch("/api/admin")
      .then((res) => res.json())
      .then((data) => {
        if (data.status === 200) {
          setUserData(data.data);
        } else {
          setUserData(null);
        }
      })
      .catch((err) => console.error("Error fetching data:", err))
      .finally(() => setLoading(false));
  }, []);

  const handleLogOut = async () => {
    const response = await fetch('/api/users/logout')

    if(response.status === 200) {
      setUserData(null);
      alert("Logged out successfully!");
      window.location.replace('/');
    } else {
      console.error("Error while logging out!");
    }
  }

  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased font-serif`}
      >
        { !hideHeader && <header>
          <div className='flex justify-between items-center h-20 p-2 bg-black'>
            <Image src={logo} alt='Logo' width={120} height={100} />
            <div className="flex">
              {userData ? 
                (userData.role == 'customer' ? 
                  <div className="flex">
                      <Link href='/components/pages/home'>
                        <div className='text-white pe-4 hover:text-gray-500 rounded-md'>Home</div>
                      </Link>
                      <div onClick={handleLogOut}>
                        <div className='me-4 px-3 hover:text-gray-500 text-black bg-green-400 rounded-md'>Logout</div>
                      </div>
                  </div>
                  : 
                  <div className="flex">
                      <Link href='/components/pages/adminHome'>
                      <div className='text-white pe-4 hover:text-gray-500 rounded-md'>Home</div>
                    </Link>
                      <div onClick={handleLogOut}>
                        <div className='me-4 px-3 hover:text-gray-500 text-black bg-green-400 rounded-md'>Logout</div>
                      </div>
                  </div>
                ) : 
                <Link href='/components/pages/signup'>
                  <div className='text-black px-5 py-1 bg-green-400 rounded-md'>SignUp</div>
                </Link>
                }
            </div>
          </div>
        </header>}
        {children}
      </body>
    </html>
  );
}
